name: Test, Build and Deploy Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Setting_python_machine:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
        cache-dependency-path: '**/cicd_requirements.txt'
        
    - name: Installing CI/CD dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r src/cicd_requirements.txt


  Testing_and_linting:
    needs: Setting_python_machine
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
        cache-dependency-path: '**/cicd_requirements.txt'
        
    - name: Installing CI/CD dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r src/cicd_requirements.txt

    - name: Lint with pylint
      run: |
        pylint ./src
        
    - name: Test with pytest
      run: |
        pytest
        
  Deploy_to_aws:
    needs: Testing_and_linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v2
        with:
          python: "3.10"
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Set repository name
        run: echo "REPOSITORY_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV

      - name: Modify template.yaml
        run: |
            sed -i "s/PlaceholderToRepoName/$REPOSITORY_NAME/g" infra/template.yaml
            REPOSITORY_NAME=$(echo $REPOSITORY_NAME | sed 's/[^a-zA-Z0-9]//g')
            sed -i "s/PlaceholderToFunctionWithoutAlphaNum/$REPOSITORY_NAME/g" infra/template.yaml
            
      - name: Modify samconfig.toml
        run: |
          
          sed -i "s/PlaceholderToFunctionWithoutAlphaNum/$REPOSITORY_NAME/g" infra/samconfig.toml
        
      # Build using SAM
      - run: sam build --template-file infra/template.yaml 
      # Deploy on AWS
      - run: echo "Y" | sam deploy --config-file=infra/samconfig.toml --no-confirm-changeset --no-fail-on-empty-changeset --debug    
